FROM python:3.12.12-bookworm
ENV DEBIAN_VERSION=12

RUN apt-get update && apt-get install gpg wget -y

RUN wget -qO- https://packages.microsoft.com/keys/microsoft.asc | \
    gpg --dearmor | tee /usr/share/keyrings/microsoft-prod.gpg

RUN wget -q https://packages.microsoft.com/config/debian/$DEBIAN_VERSION/prod.list && \
    mv prod.list /etc/apt/sources.list.d/microsoft-prod.list

RUN apt-get update && apt-get install azure-functions-core-tools-4 libicu-dev pipx -y

ENV PATH="$PATH:/root/.local/bin"

RUN pipx install poetry==2.2

WORKDIR /functions/
COPY functions/ /functions/
COPY api/ /api/

RUN poetry install

CMD poetry install && \
    poetry run python create_containers.py && \
    poetry run func start --port 7071
