repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black
        args:
          - --config=api/pyproject.toml
-   repo: https://github.com/pycqa/flake8
    rev: 7.1.2
    hooks:
    -   id: flake8
        args:
          - --config=api/.flake8

