"""Create validation table

Revision ID: 1b70b69c9d41
Revises: 25176868d0a9
Create Date: 2025-02-08 15:15:55.498179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b70b69c9d41'
down_revision: Union[str, None] = '25176868d0a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_validation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lesson_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('validated', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('validated_success', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('validated_value', sa.Float(), nullable=True),
    sa.Column('media_path', sa.String(), nullable=False),
    sa.Column('media_type', sa.Enum('IMAGE', 'VIDEO', name='mediatype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ondelete='no action'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='no action'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('lesson_user', sa.Column('validated_success', sa.Boolean(), server_default='FALSE', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson_user', 'validated_success')
    op.drop_table('lesson_validation')
    # ### end Alembic commands ###
