"""Change lesson user primary key

Revision ID: 7f14effd8396
Revises: 1b70b69c9d41
Create Date: 2025-03-04 20:40:25.654358

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7f14effd8396"
down_revision: Union[str, None] = "1b70b69c9d41"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("lesson_user_pkey", "lesson_user")
    op.add_column("lesson_user", sa.Column("id", sa.Uuid(), nullable=False))
    op.create_primary_key("lesson_user_pkey", "lesson_user", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("lesson_user_pkey", "lesson_user")
    op.drop_column("lesson_user", "id")
    op.create_primary_key("lesson_user_pkey", "lesson_user", ["lesson_id", "user_id"])
    # ### end Alembic commands ###
