"""Create foreign key on validation table

Revision ID: d13f31069b13
Revises: 7f14effd8396
Create Date: 2025-03-04 21:08:28.977116

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d13f31069b13"
down_revision: Union[str, None] = "7f14effd8396"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "lesson_validation", sa.Column("lesson_user_id", sa.Uuid(), nullable=False)
    )
    op.create_foreign_key(
        "lesson_validation_lesson_user_id_fkey",
        "lesson_validation",
        "lesson_user",
        ["lesson_user_id"],
        ["id"],
        ondelete="no action",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "lesson_validation_lesson_user_id_fkey", "lesson_validation", type_="foreignkey"
    )
    op.drop_column("lesson_validation", "lesson_user_id")
    # ### end Alembic commands ###
