"""Add identity validation table

Revision ID: d6294ab12aba
Revises: 7854bebd271c
Create Date: 2025-09-15 21:23:12.560227

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql as pg


# revision identifiers, used by Alembic.
revision: str = "d6294ab12aba"
down_revision: Union[str, None] = "7854bebd271c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "identity_validation",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("validated", sa.Boolean(), nullable=False),
        sa.Column("validated_success", sa.Boolean(), nullable=False),
        sa.Column("image_path", sa.String(), nullable=False),
        sa.Column("identity_code", sa.String(), nullable=True),
        sa.Column("identity_code_confidence", sa.Float(), nullable=True),
        sa.Column(
            "type",
            pg.ENUM(name="identitytype", create_type=False),
            nullable=True,
        ),
        sa.Column("type_confidence", sa.Float(), nullable=True),
        sa.Column("fullname", sa.String(), nullable=True),
        sa.Column("fullname_confidence", sa.Float(), nullable=True),
        sa.Column("parent_fullname", sa.String(), nullable=True),
        sa.Column("parent_fullname_confidence", sa.Float(), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("birth_date_confidence", sa.Float(), nullable=True),
        sa.Column("expiration_date", sa.Date(), nullable=True),
        sa.Column("expiration_date_confidence", sa.Float(), nullable=True),
        sa.Column("issued_date", sa.Date(), nullable=True),
        sa.Column("issued_date_confidence", sa.Float(), nullable=True),
        sa.Column("issuing_authority", sa.String(), nullable=True),
        sa.Column("issuing_authority_confidence", sa.Float(), nullable=True),
        sa.Column("country_state", sa.String(), nullable=True),
        sa.Column("country_state_confidence", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("identity_validation")
    # ### end Alembic commands ###
