from os import environ


VISION_ENDPOINT = environ["VISION_ENDPOINT"]
VISION_APIKEY = environ["VISION_APIKEY"]
DOCUMENT_INTELLIGENCE_LOCALE = "pt"
DOCUMENT_INTELLIGENCE_ENDPOINT = environ["DOCUMENT_INTELLIGENCE_ENDPOINT"]
DOCUMENT_INTELLIGENCE_APIKEY = environ["DOCUMENT_INTELLIGENCE_APIKEY"]
