FROM python:3.12-alpine3.19

WORKDIR /api/

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY api /api/api

ENV PORT=8000
CMD fastapi run api/app.py --host "0.0.0.0" --port $PORT
