FROM python:3.12-alpine3.19

# Install pipx and poetry
ENV SHELL=sh
ENV PATH="$PATH:/root/.local/bin"
RUN apk add 'pipx=~1.4'
RUN pipx install poetry==2.1

WORKDIR /api/
COPY . /api/
RUN poetry install

CMD ["poetry", "run", "fastapi", "dev", "api/app.py", "--host", "0.0.0.0"]
