# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install PIPX
      run: |
        sudo apt install pipx
        pipx ensurepath
    - name: Install Poetry
      run: pipx install poetry==2.0.0
    - name: Install dependencies
      run: poetry install --with=dev
    - name: Black code checking
      run: poetry run black --check .
    - name: Flake8 code checking
      run: poetry run flake8 .
    - name: Run fastest tests
      run: poetry run pytest -m "not slow"
    - name: Run slow tests
      run: poetry run pytest -m slow
